AllCops:
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  Exclude:
    - '*_test.rb'
Metrics/AbcSize:
  Exclude:
    - '*_test.rb'
Metrics/ClassLength:
  Exclude:
  - '*_test.rb'
Metrics/MethodLength:
  Max: 120
  Exclude:
    - '*_test.rb'
Style/Documentation:
  Enabled: false
